post '/merge_requests/event', to: 'merge_requests#event'
get '/projects/:id/merge_requests/token', to: 'token#index'
get '/projects/:id/merge_requests/token/:provider', to: 'token#view'
post '/projects/:id/merge_requests/token/:provider', to: 'token#create'
patch '/projects/:id/merge_requests/token/:provider', to: 'token#edit'
get '/projects/:id/merge_requests/token/:provider/delete', to: 'token#delete'
delete '/projects/:id/merge_requests/token/:provider', to: 'token#delete'
